---
title: "Cloning Success Rates"
author: "Kenneth Matreyek"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
rm(list = ls())
library(tidyverse)
```

```{r Part 1}
input_data <- read.csv(file = "MatreyekLab_Hifi_Reactions - colonies_success_rates.csv", header = T, stringsAsFactors = F)
input_data$comb_rate <- as.numeric(input_data$comb_rate)

gibson <- input_data %>% filter(!is.na(comb_rate)) %>% group_by(gibson, parts) %>% add_tally() %>% summarize(mean = mean(comb_rate), sd = sd(comb_rate), n = median(n))

parts1_gibson <- input_data %>% filter(!is.na(parts) & !is.na(tested) & parts == 1 & gibson == "yes")
parts1_gibson <- data.frame("comb_rate" = parts1_gibson$comb_rate, "parts" = 1, "gibson" = "yes")
parts2_gibson <- input_data %>% filter(!is.na(parts) & !is.na(tested) & parts == 2 & gibson == "yes")
parts2_gibson <- data.frame("comb_rate" = parts2_gibson$comb_rate, "parts" = 2, "gibson" = "yes")
parts1_nogibson1 <- input_data %>% filter(!is.na(parts) & !is.na(tested) & parts == 1 & gibson == "no") 
parts1_nogibson1[parts1_nogibson1$muts_of == "","muts_of"] <- seq(1,sum(parts1_nogibson1$muts_of == ""))
parts1_nogibson <- parts1_nogibson1 %>% group_by(muts_of) %>% summarize(comb_rate = mean(comb_rate), parts = unique(parts), gibson = unique(gibson)) %>% select(-muts_of)
parts1_nogibson <- data.frame("comb_rate" = parts1_nogibson$comb_rate, "parts" = 1, "gibson" = "no")
parts2_nogibson <- input_data %>% filter(!is.na(parts) & !is.na(tested) & parts == 2 & gibson == "no")
parts2_nogibson <- data.frame("comb_rate" = parts2_nogibson$comb_rate, "parts" = 2, "gibson" = "no")

combined_frame <- rbind(parts1_gibson, parts2_gibson, parts1_nogibson, parts2_nogibson)
combined_frame[combined_frame$parts == 1,"parts"] <- "1-part"
combined_frame[combined_frame$parts == 2,"parts"] <- "2-parts"

Gibson_plot <- ggplot() + theme_bw() + theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank()) + 
  geom_density(data = combined_frame, aes(x = comb_rate, y = ..count.., fill = gibson), alpha = 0.3, 
position="stack") +
  facet_grid(rows = vars(parts)) + xlab("Rate of success") + ylab("Number of reactions") +
  geom_vline(xintercept = 0.75, linetype = 2, color = "blue") +
  geom_vline(xintercept = 0.25, linetype = 2, color = "red")
ggsave(file = "Gibson_plot.pdf", Gibson_plot, height = 3, width = 4)
Gibson_plot
```

```{r Part two}
# Make another set of plots using the above data to show how often it "works immediately", "works with some struggle", and simply "does not work"

temp <- ggplot_build(ggplot() + geom_density(data = combined_frame, aes(x = comb_rate, y = ..count.., fill = gibson), alpha = 0.3))

part2 <- data.frame(temp$data) %>% filter(group == 2)
part1 <- data.frame(temp$data) %>% filter(group == 1)

With_gibson_density_plot <- ggplot() + 
  theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_continuous(limits = c(0,1), expand = c(0,0)) +
  scale_y_continuous(limits = c(0,1.1), expand = c(0,0)) +
  labs(x = "Frequency of successful clones per Gibson attempt", y = "Relative density\n(fraction of maximum)") +
  geom_point(data = part1, aes(x = x, y = density), color = "#F8766D") #with Gibson
With_gibson_density_plot
ggsave(file = "With_gibson_density_plot.pdf", With_gibson_density_plot, height = 3, width = 5)
ggsave(file = "/Users/kmatreyek/Dropbox/Website/Plots/With_gibson_density_plot.png", With_gibson_density_plot, height = 3, width = 5)

#ggplot() + geom_point(data = part2, aes(x = x, y = density), color = "#00BFC4") #without Gibson
probs <- data.frame("probability" = sample_n(part1, 100, weight = part1$density)$x)

output_frame <- data.frame("clones" = rep(seq(0,5),50), "successes_in_hundred" = 0)
for(x in 1:nrow(output_frame)){
  result_vector <- c()
  for(y in seq(1,100)){
    temp_probability <- sample_n(part1, 1, weight = part1$density)$x
    temp_clone_results <- rbinom(output_frame$clones[x], 1, prob = temp_probability)
    temp_success <- 1 %in% temp_clone_results
    result_vector <- c(result_vector, temp_success)
  }
  output_frame[x,"successes_in_hundred"] <- sum(result_vector)
}
output_frame
output_frame$fraction_successful <- output_frame$successes_in_hundred / 100
output_frame_summarized <- output_frame %>% group_by(clones) %>% summarize(mean = mean(fraction_successful),
                                                                                       sd = sd(fraction_successful))
Bootstrapped_clone_screening_simulation <- ggplot() + 
  theme_bw() + 
  theme(panel.grid.minor = element_blank(), panel.grid.major.x = element_blank()) +
  labs(x = "Number of clones screened by miniprep + sequencing",
       y = "Fraction of times screening\nthe indicated number of clones\nyielded at least one successful clone\n") +
  scale_y_continuous(limits = c(0,1)) + 
  geom_hline(yintercept = 0) +
  geom_hline(yintercept = 1) +
  geom_line(data = output_frame_summarized, aes(x = clones, y = mean), alpha = 0.4) +
  geom_errorbar(data = output_frame_summarized, aes(x = clones, ymin = mean - sd*1.96, ymax = mean + sd*1.96)
                , width = 0.1, alpha = 0.6) + 
  geom_point(data = output_frame_summarized, aes(x = clones, y = mean))
ggsave(file = "Bootstrapped_clone_screening_simulation.pdf", Bootstrapped_clone_screening_simulation, height = 3, width = 5)
Bootstrapped_clone_screening_simulation
```